version: "3.8"

services:
  app:
    build:
      context: .
      target: dev-stage
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/project/src
      - ./tests:/project/tests
      - ./main.py:/project/main.py
      - ./data:/project/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./.volume/data:/data
